### ISSUE TITLE
Bug: Patch release 1.1.12 breaks type inference with `.into()` on `EnumSet` methods — semver violation

### ISSUE THREAD

**Issue by pamburus** [Lymia/enumset#84]
**enumset version:** 1.1.10 (works) → 1.1.12 (broken)
**Rust edition:** 2024
**rustc:** stable

### Description

Upgrading `enumset` from `1.1.10` to `1.1.12` (a patch release) breaks compilation of code that previously compiled fine. This constitutes a **semver violation**: a patch release must not introduce breaking
changes per [Semantic Versioning 2.0.0 §6](https://semver.org/#spec-item-6).

### Minimal reproduction

```rust
use enumset::{EnumSet, EnumSetType};

#[derive(EnumSetType)]
enum Foo { A, B, C }

fn main() {
    let set: EnumSet<Foo> = EnumSet::all();
    let _ = set.difference(Foo::A.into()); // compiles on 1.1.10, fails on 1.1.12
}
```

### Error on 1.1.12

```
error[E0283]: type annotations needed
  --> src/main.rs:8:35
   |
8  |     let _ = set.difference(Foo::A.into());
   |             ----------     ^^^^
   |             |
   |             required by a bound introduced by this call
   |
   = note: cannot satisfy `_: Into<enumset::EnumSet<Foo>>`
note: required by a bound in `enumset::EnumSet::<T>::difference`
  --> enumset-1.1.12/src/impl_set.rs:145:5
   |
145|     set_common_methods!(T, T::Repr);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `EnumSet::<T>::difference`
```

### Root cause

The `set_common_methods!` macro in `1.1.12` introduces additional `Into` bounds on methods like `difference`. These new bounds make `into()` calls ambiguous to the type inference engine — it can no longer
determine which `Into<_>` implementation to use — where previously inference succeeded unambiguously.

### Impact

Any crate depending on `enumset = "1"` (or `"^1.1"`) is silently pulled to `1.1.12` and breaks. The fix (either annotating the type or removing `.into()`) requires downstream code changes that were not
necessary before.

**Real-world example:** [pamburus/hl#1428](https://github.com/pamburus/hl/pull/1428) — a dependent crate broken by this upgrade with no changes of its own.

The crate does not depend on `enumset_derive` directly (it is a transitive dependency of `enumset`), and the only command run was `cargo update enumset`, nothing else changed.

### Workaround

Pin to `1.1.10` in `Cargo.toml`:

```toml
enumset = "=1.1.10"
```

or replace `.into()` with a direct value (removing the ambiguity):

```rust
// before
set.difference(Foo::A.into())

// after (explicit single-element set)
set.difference(EnumSet::only(Foo::A))
// or simply pass the variant directly if the method accepts T
set.difference(Foo::A)
```

### Expected behavior

A patch release should not require any changes in dependent code. The new bounds should either be backwards-compatible or shipped in a minor/major release.

The key facts: set_common_methods! gained new Into bounds in 1.1.12 that introduce type ambiguity where inference previously worked, and since this is a patch bump it's a clear semver violation.

**Comment by Lymia** [comment]
1.1.13 has been published to correct this issue.

**Comment by pamburus** [comment]
Thanks, it works.
